name: 自动同步脚本更新

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月的第一天凌晨 12 点自动同步
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出 fork 仓库
      - name: Checkout the fork repository
        uses: actions/checkout@v3
        with:
          ref: main  # 确保同步的是主分支

      # 设置 Git 配置
      - name: Set Git global config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # 添加主项目为上游仓库
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/<your-username>/<upstream-repository>.git
          git fetch upstream

      # 合并主项目的最新提交到 fork 仓库
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit

      # 推送合并后的更改到 fork 仓库
      - name: Push changes to fork
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
