name: 此工作流仅为测试使用

on:
  schedule:
    # 每天凌晨 1 点运行
    - cron: '0 1 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # 安装依赖库 requests
    - name: Install requests library
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # 运行 Python 脚本
    - name: Run Python script
      run: |
        python test.py  # 替换为你要运行的 Python 脚本
